POST http://localhost:5000/api/user/add
Content-Type: application/json; charset=utf-8

{
    "name": "asdsadasdasd",
    "userName": "sdfsfsdf",
    "email": "sdfsdfsdf@sdfsdfsdf.com",
    "phoneNumber": "22446122",
    "address": "kaninhullet 14"
}